---
- hosts: serverklient1
  become: yes
  tasks:
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    # Set root password and force modern plugin (MySQL 8+)
    - name: Set root password and plugin to caching_sha2_password
      shell: |
        mysql --protocol=socket -uroot -e "
          ALTER USER 'root'@'localhost'
          IDENTIFIED WITH caching_sha2_password BY 'qwerty';
          FLUSH PRIVILEGES;
        "
      args:
        executable: /bin/bash

    - name: Create /root/.my.cnf (0600)
      copy:
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'
        content: |
          [client]
          user=root
          password=qwerty
          host=localhost
          socket=/var/run/mysqld/mysqld.sock

